#!/bin/bash

# create several indexes from nr and nt databases
# Mark Stenglein 8.6.2013  
#
# This script builds the indexes in a dated sub-directory
# and then copies them back to main directory, overwriting 
# old versions of the indexes.
#
# NOTE that this could possibly interfere w/ running 
# diamond, gsnapl, hisat, etc. processes
#
#

# build database indexes
echo "*************************************************"
echo "*** building indexes from nr and nt databases ***"
echo "*************************************************"

# build new indices in a separate directory
# create it and then cd there

today=`date +%Y_%m_%d`
index_dir=indexes_${today}
mkdir $index_dir
cd $index_dir

# download nr & nt dbs in fasta format 
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz
wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nt.gz
gunzip nt.gz 
gunzip nr.gz 

# rename to have .fasta extension
mv nt nt.fasta
mv nr nr.fasta

echo "creating diamond index of nr database"
date

echo "downloading taxonomy accession -> taxid mapping information from NCBI"
rm -f prot.accession2taxid.FULL.gz*
rm -f taxdmp.zip*
rm -f names.dmp*
rm -f nodes.dmp*
curl -OL ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz
curl -OL ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip
unzip taxdmp.zip
rm -f taxdmp.zip

diamond makedb --in nr.fasta -d nr --taxonmap prot.accession2taxid.FULL.gz --taxonnames names.dmp --taxonnodes nodes.dmp --threads 32
mv nr.dmnd ..


# fasta files
mv nr.fasta ..
mv nt.fasta ..

echo "done rebuilding indexes"
date

echo "done rebuilding indexes" > indexes_built.txt
date >> indexes_built.txt

cp indexes_built.txt ..
