#!/bin/bash

# Usage info:
usage()
{
cat << EOF
 
 This script downloads a dataset or multiple datasets from the NCBI Short Read Archive (SRA)

 The datasets are downloaded as .fastq format files.

 This script accepts SRA Run accessions (SRRXXXXXX) as arguments and can accept a file with
 multiple accessions, one per line.

 See also: http://www.ncbi.nlm.nih.gov/books/NBK158899/


 Mark Stenglein June 3, 2016

 Dependencies: 
  (1) internet access
  (2) wget or curl

 Usage:

  download_sra_data <SRR_acc_1> [ ... <SRR_acc_N>] [-h] [-f filename]

  -h           print this message

  -f filename  specify a filename with multiple SRA run accessions, one per line

  -r           rename downloaded files from XXX_1.fastq and XXX_2.fastq to XXX_R1.fastq XXX_R2.fastq

  SRR_acc_N    SRA run accessions of dataset to download, of form SRRXXXXXXX


 Usage examples:

  download_sra_data SRR1539827 SRR1539826 SRR1539825

  download_sra_data -f file_with_list_of_SRR_accessions.txt


EOF
}

# if no arguments, don't stall
# if [[ -t 0 ]] && [[ $# -eq 0 ]]
if [[ $# -eq 0 ]]
then
  usage
  exit
fi

# initialize some variables
accession_filename=""
accessions=()
rename_files=0

# parse command line options
while getopts “hrf:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         f)
             # download a bunch of SRA datasets, listed in a file
             accession_filename=$OPTARG
             ;;
         r)
             # rename files
             rename_files=1
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

# shift off used up args
shift $((OPTIND-1))

# if a file w/ accession #s, read them into an array
if [[ !  -z  $accession_filename  ]] 
then
   while read -r line
   do
		# ignore comment lines
		[[ "$line" =~ ^#.*$ ]] && continue
	   accessions+=("$line")
   done < "$accession_filename"
fi

# other accessions = rest of arguments
accessions+=("$@")

for sra_acc in "${accessions[@]}"
do
	# does this look like a legit SRA run accession?
	if [[ $sra_acc  =~ [DES]"RR"[0-9]+ ]] 
	then

      # check to see if fastq-dump exists
      if [ -x "$(command -v fastq-dump)" ] 
		then
         # : does nothing
			:
		else 
         echo 'Error: fastq-dump not found.  Exiting.' >&2
			exit
      fi

		# actually get the data using wget or curl
	   echo "fastq-dump -I --split-files $sra_acc"
	   fastq-dump -I --split-files $sra_acc
		if [[ "$rename_files" -eq "1" ]]
		then
		   mv ${sra_acc}_1.fastq ${sra_acc}_R1.fastq 
			if [ -e ${sra_acc}_2.fastq ]
			then
		      mv ${sra_acc}_2.fastq ${sra_acc}_R2.fastq 
			fi
		fi
	else
		# invalid run accession format
	   echo "warning: $sra_acc does not appear to be an SRA run accession ([SDE]RRXXXXXX), skipping\n" 
	fi

done 



