#!/usr/bin/perl

# this script outputs spade contigs within a particular coverage range
#
# Mark Stenglein August 29, 2011
#

use strict;
use Getopt::Long;

my $usage = <<USAGE;

  This script reads a SPADES assembler-created fasta file (of SPADES contigs)
  and outputs the name of each contig as well as its average coverage level.
  It determines average coverage level from the fasta header, which it expects
  to look something like:

  NODE_60_length_1427_cov_551.724_ID_119


  Reads from stdin and writes to stdout. 

  Mark Stenglein 10/26/2015


  usage: $0 [-h] [-n] <spade_contigs_fasta_file>

     -h          print this help msg

     -n          don't output the names of the contigs, only output the average 
                 coverage

USAGE



if ( -t STDIN and not @ARGV) { print $usage and exit; }

my $do_not_print_names = 0;
my $print_usage = 0;

GetOptions ("h" => \$print_usage, "n" => \$do_not_print_names);

if ($print_usage) { print $usage; exit; }

my $printing_lines = 0;

while (<>)
{
   chomp;
   if (/^>(.*)/)
   {
      my $header = $1;

      # cov_551.724_ID
      if (/cov_(\d*\.?\d+)_ID/)
      {
         my $coverage_level = $1;
         if ($do_not_print_names)
         {
            print "$coverage_level\n";
         }
         else
         {
            print "$header\t$coverage_level\n";
         }
      }
   }
}

