#!/bin/bash

# count records in fastq files

usage="fastq_count [-s] [-e] <fastq_file_1> ... <fastq_file_n>"

silent=0
estimated=0

while getopts "se" optname
  do
    case "$optname" in
      "s")
        silent=1
        ;;
      "h")
        echo "$usage"
        exit
        ;;
      "e")
        estimated=1
        ;;
      "?")
        echo "$usage"
        exit
        ;;
    esac
  done

# shift away the options
shift $((OPTIND-1))

big_count=0
for file in "$@"
do
   if [ $estimated -eq 1 ]; then
      count=`estimated_fastx_count $file`
   else
      line_count=`wc -l $file | cut -f 1 -d " "`
      count=$(( line_count / 4 ))
   fi

   big_count=`expr $count + $big_count`
 
   if [ $silent -eq 1 ]; then
      printf "$count\n";
   else
      printf "$file\t$count\n";
   fi
done

if [ $silent -eq 0 ]; then
   printf "total\t$big_count\n"
fi


