#!/bin/bash
# 
# setup mysql datbases for stenglein lab servers
#
# Mark Stenglein 7.27.2017
#

# First, move mysql db to /home, and populate it with NCBI Taxonomy info
# 
# Move mysql data directory
# see:
# https://stackoverflow.com/questions/1795176/how-to-change-mysql-data-directory
#
echo "-----------------------------------------------------------"
echo "going to do some major work on my sql databases"
echo "(move data directory, create new dbs and users, etc.)"
echo " "
read -p " *** Are you sure you want to continue? ***   (y or Y to continue): " -n 1 -r
echo " "
if [[ $REPLY =~ ^[Yy]$ ]]
then
   continue
else
   exit
fi

echo moving mysql data directory
echo "see: https://stackoverflow.com/questions/1795176/how-to-change-mysql-data-directory"

echo "sudo /etc/init.d/mysql stop"
sudo /etc/init.d/mysql stop

echo "sudo cp -R -p /var/lib/mysql /home/databases"
sudo cp -R -p /var/lib/mysql /home/databases

echo "need to edit my.cnf file.  "
echo "change datadir from /var/lib/mysql to /home/databases/mysql"
# TODO: could use sed to to this

echo going to vi now
echo enter to continue
read x

sudo vi /etc/mysql/mysql.conf.d/mysqld.cnf 

echo "now need to edit AppArmour config file"
echo "Look for lines beginning with /var/lib/mysql. Change /var/lib/mysql to reflect the new path."

echo going to vi now
echo enter to continue
read x
sudo vi /etc/apparmor.d/usr.sbin.mysqld

echo "sudo /etc/init.d/apparmor reload"
sudo /etc/init.d/apparmor reload

echo "sudo /etc/init.d/mysql restart"
sudo /etc/init.d/mysql restart

# now, create a new database and a corresponding user for NCBI_Taxonomy usage
echo "going go create a new table in mysql and an NCBI_Taxonomy user.  Will be prompted for (mysql) root user password"
echo enter to continue
read x

sql_file=/tmp/sql_setup_$$

cat > $sql_file << SQL_FILE

CREATE DATABASE NCBI_Taxonomy;
CREATE USER 'NCBI_Taxonomy'@'localhost' IDENTIFIED BY 'NCBI_Taxonomy';
GRANT ALL PRIVILEGES ON NCBI_Taxonomy.* TO 'NCBI_Taxonomy'@'localhost';
GRANT FILE on *.* to 'NCBI_Taxonomy'@'localhost';

FLUSH PRIVILEGES;

SQL_FILE

cat $sql_file | mysql -u root -p

rm $sql_file




